genlib.o: genlib.c genlib.h exception.h gcalloc.h
    $(CC) $(CFLAGS) -c genlib.c

bst.o: bst.c bst.h cmpfn.h genlib.h
    $(CC) $(CFLAGS) -c bst.c

cmpfn.o: cmpfn.c cmpfn.h strlib.h genlib.h
    $(CC) $(CFLAGS) -c cmpfn.c

iterator1.o: iterator1.c iterator1.h genlib.h strlib.h symtab.h
    $(CC) $(CFLAGS) -c iterator1.c

iterator2.o: iterator2.c iterator2.h cmpfn.h genlib.h itertype.h
    $(CC) $(CFLAGS) -c iterator2.c

queue.o: queue.c queue.h genlib.h
    $(CC) $(CFLAGS) -c queue.c

queuelist.o: queuelist.c queuelist.h genlib.h
    $(CC) $(CFLAGS) -c queuelist.c

random.o: random.c random.h genlib.h
    $(CC) $(CFLAGS) -c random.c

ref.o: ref.c ref.h genlib.h
    $(CC) $(CFLAGS) -c ref.c

scanadt.o: scanadt.c scanadt.h genlib.h strlib.h
    $(CC) $(CFLAGS) -c scanadt.c

set.o: set.c set.h bst.h genlib.h iterator2.h itertype.h
    $(CC) $(CFLAGS) -c set.c

foreach.o: foreach.c foreach.h genlib.h iterator2.h
    $(CC) $(CFLAGS) -c foreach.c

simpio.o: simpio.c simpio.h strlib.h genlib.h
    $(CC) $(CFLAGS) -c simpio.c

stack.o: stack.c stack.h genlib.h
    $(CC) $(CFLAGS) -c stack.c

stacklist.o: stacklist.c stacklist.h genlib.h
    $(CC) $(CFLAGS) -c stacklist.c

strlib.o: strlib.c strlib.h genlib.h
    $(CC) $(CFLAGS) -c strlib.c

symtab.o: symtab.c symtab.h strlib.h genlib.h itertype.h cmpfn.h
    $(CC) $(CFLAGS) -c symtab.c

exception.o: exception.c exception.h genlib.h
    $(CC) $(CFLAGS) -c exception.c

graphics.o: graphics.c graphics.h extgraph.h xmanager.h xcompat.h \
            glibrary.h genlib.h gcalloc.h simpio.h strlib.h Makefile
    $(CC) $(CONFIG) $(CFLAGS) -c graphics.c

xmanager.o: xmanager.c xmanager.h xdisplay.h xcompat.h glibrary.h \
        genlib.h exception.h simpio.h Makefile
    $(CC) $(CONFIG) $(CFLAGS) -c xmanager.c

xdisplay.o: xdisplay.c xdisplay.h xmanager.h glibrary.h genlib.h strlib.h \
            Makefile
    $(CC) $(CONFIG) $(CFLAGS) -c xdisplay.c

xcompat.o: xcompat.c xcompat.h Makefile
    $(CC) $(CONFIG) $(CFLAGS) -c xcompat.c

glibrary.o: glibrary.c glibrary.h genlib.h
    $(CC) $(CFLAGS) -c glibrary.c